Release a lock that is no longer used
chaos/pdsh pull request #138
Opened 2021-09-09 02:52 UTC by ycaibb

Release a lock threadcount_mutex that is no longer used

Signed-off-by: ycaibb <ycaibb@gmail.com>

2021-09-09 18:27 UTC, grondo commented
Can you more explicitly describe the problem in the commit message, e.g. something like:

>  In dsh(), the threadcount_mutex is never released. While technically not a bug, this could cause a problem or confusion in the future if a lock is attempted on the mutex.

Then describe the fix. I think this will help future developers when looking at project history.

2021-09-10 06:37 UTC, ycaibb commented
@grondo  Hi, I have revised the commit message.

2021-09-10 16:53 UTC, grondo requested changes
Thanks! I've noted a couple requested minor changes inline.

2021-09-10 16:53 UTC, grondo commented on src/pdsh/dsh.c
> +
Can you fix this whitespace error?
```suggestion

```

2021-09-10 16:53 UTC, grondo commented on src/pdsh/dsh.c
> +
Also, please wrap commit message body at 72 columns when possible.
A description of why (and what makes a good commit message) can be found [here](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

2021-09-11 03:05 UTC, ycaibb commented on src/pdsh/dsh.c
> +
Please take a look, Thanks~

2021-09-13 16:10 UTC, grondo approved these changes
LGTM, thanks!

2021-09-13 16:14 UTC, merged